// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDerysFEbeL74jzqSei1KCZaalfuwQe2uo',
    appId: '1:796247539867:web:9c68b30f5cd03336e2463e',
    messagingSenderId: '796247539867',
    projectId: 'tailwag-289ab',
    authDomain: 'tailwag-289ab.firebaseapp.com',
    storageBucket: 'tailwag-289ab.appspot.com',
    measurementId: 'G-2GKDHC12PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBfyIsXiBHhJ0SZiLQzwaczY8UyJz8SY',
    appId: '1:796247539867:android:b232c1b3dc4f91bce2463e',
    messagingSenderId: '796247539867',
    projectId: 'tailwag-289ab',
    storageBucket: 'tailwag-289ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXW6-0YI1S4oldmcyvH51EobWrCAU5q4',
    appId: '1:796247539867:ios:68f93f97d2e44453e2463e',
    messagingSenderId: '796247539867',
    projectId: 'tailwag-289ab',
    storageBucket: 'tailwag-289ab.appspot.com',
    iosBundleId: 'com.example.tailwag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpXW6-0YI1S4oldmcyvH51EobWrCAU5q4',
    appId: '1:796247539867:ios:63efc7cc4ea3d99ae2463e',
    messagingSenderId: '796247539867',
    projectId: 'tailwag-289ab',
    storageBucket: 'tailwag-289ab.appspot.com',
    iosBundleId: 'com.example.tailwag.RunnerTests',
  );
}
